apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway
  namespace: default
data:
  SPRING_MAIN_CLOUD_PLATFORM: 'kubernetes'
  SPRING_PROFILES_ACTIVE: 'k8s'
  SPRING_DATA_REDIS_URL: 'redis://:Test1234@redis.database:6379'
  SPRING_CLOUD_CONFIG_URI: 'http://config-centralized.core:8888/'
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: 'http://zipkin.core:9411/api/v2/spans'
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eureka.core:8080/eureka'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: default
  labels:
    k8s-app: gateway
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: gateway
  template:
    metadata:
      labels:
        k8s-app: gateway
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.96.0.10
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "2"
          - name: edns0
      containers:
        - name: gateway
          image: laminalfalah/gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TZ
              value: Asia/Jakarta
          envFrom:
            - configMapRef:
                name: gateway
          livenessProbe:
            httpGet:
              port: http
              path: /livez
            periodSeconds: 60
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: http
              path: /readyz
            periodSeconds: 60
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - name: spring-log
              mountPath: /home/gateway/data/logs
      volumes:
        - name: spring-log
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: default
spec:
  type: LoadBalancer
  selector:
    k8s-app: gateway
  ports:
    - name: http
      port: 8080
      targetPort: http
